# Generated by Django 5.2.7 on 2026-01-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('employment_status', models.CharField(max_length=50)),
                ('field_of_work', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('ready_for_interview', models.CharField(max_length=50)),
                ('premium_interest', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
