# Generated by Django 5.2.7 on 2026-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='field_of_work',
        ),
        migrations.RemoveField(
            model_name='application',
            name='premium_interest',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ready_for_interview',
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, help_text='Which CTA user clicked', max_length=50),
        ),
    ]
