# Generated by Django 5.2.7 on 2026-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_application_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags e.g. hot,priority,backend', max_length=200),
        ),
    ]
